# -*- coding: utf-8 -*-
"""Olist_Supply_Chain_Part1_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eklLuc4L8UO3A1KuMBrPvhhp4iFlQnC1
"""

import os
print(os.listdir())

import pandas as pd
import numpy as np
from datetime import datetime

orders = pd.read_csv('/content/olist_orders_dataset.csv')
order_items = pd.read_csv('/content/olist_order_items_dataset.csv')
customers = pd.read_csv('/content/olist_customers_dataset.csv')
products = pd.read_csv('/content/olist_products_dataset.csv')
sellers = pd.read_csv('/content/olist_sellers_dataset.csv')
order_payments = pd.read_csv('/content/olist_order_payments_dataset.csv')
order_reviews = pd.read_csv('/content/olist_order_reviews_dataset.csv')
product_category = pd.read_csv('/content/product_category_name_translation.csv')

print("All files loaded successfully!")
print("Orders shape:", orders.shape)

date_columns = ['order_purchase_timestamp', 'order_approved_at',
                'order_delivered_carrier_date', 'order_delivered_customer_date',
                'order_estimated_delivery_date']

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col], errors='coerce')

print("Date columns converted successfully!")
print(orders[date_columns].dtypes)

# Feature Engineering: Compute fulfillment duration & delay metrics
# Total lead time in days (Purchase to Customer Delivery)
orders['lead_time'] = (orders['order_delivered_customer_date'] - orders['order_purchase_timestamp']).dt.days

# Variance against target SLA date (Positive values denote late arrivals)
orders['delivery_delay'] = (orders['order_delivered_customer_date'] - orders['order_estimated_delivery_date']).dt.days

# Target flag for late deliveries
orders['is_delayed'] = orders['delivery_delay'].apply(lambda x: 1 if x > 0 else 0)

print("New features created:")
print(orders[['lead_time', 'delivery_delay', 'is_delayed']].head(10))

# Filter dataset for completed orders to maintain metric integrity
orders = orders[orders['order_status'] == 'delivered']

# Exclude records missing fulfillment timestamps
orders = orders.dropna(subset=['lead_time', 'delivery_delay'])

print("Orders after cleaning:", orders.shape)
print("Average Lead Time (days):", round(orders['lead_time'].mean(), 2))
print("Percentage of Delayed Orders: {:.2f}%".format(orders['is_delayed'].mean() * 100))

# Merge product category translation
products = products.merge(product_category, on='product_category_name', how='left')

order_items_clean = order_items[['order_id', 'product_id', 'seller_id', 'price', 'freight_value']]

print("Order items ready:", order_items_clean.shape)

# Merging everything into one main table
df = orders.merge(order_items_clean, on='order_id', how='left')
df = df.merge(products[['product_id', 'product_category_name_english']], on='product_id', how='left')
df = df.merge(customers[['customer_id', 'customer_state']], on='customer_id', how='left')
df = df.merge(sellers[['seller_id', 'seller_state']], on='seller_id', how='left')

print("Master dataset created!")
print("Shape:", df.shape)
print(df.columns.tolist())

# Target feature selection for dashboard visualization
columns_to_keep = [
    'order_id',
    'order_purchase_timestamp',
    'order_delivered_customer_date',
    'order_estimated_delivery_date',
    'lead_time',
    'delivery_delay',
    'is_delayed',
    'customer_state',
    'seller_state',
    'product_category_name_english',
    'price',
    'freight_value'
]

df_clean = df[columns_to_keep].copy()

# Calculate total transaction value per line item
df_clean['total_value'] = df_clean['price'] + df_clean['freight_value']

print("Clean dataset shape:", df_clean.shape)
print(df_clean.head())

# Perform final data quality check and summary profiling
print("Missing values:")
print(df_clean.isnull().sum())

print("\nBasic Statistics:")
print(df_clean[['lead_time', 'delivery_delay', 'total_value']].describe())

# Export staging file for dashboard consumption (e.g., Tableau, Power BI, Streamlit)
df_clean.to_csv('olist_supply_chain_cleaned.csv', index=False)
print("Cleaned file saved successfully as 'olist_supply_chain_cleaned.csv'")